### ISSUE TITLE
11

### ISSUE THREAD

**Issue by mixaron** [mixaron/1weqe#1]
Этот вопрос может быть интересен владельцам сайтов, которые хотят добавить эффектную HTML-страницу с часами. Для создания таких часов вам понадобятся знания HTML, CSS и JavaScript. Вот пример кода:

HTML:

```html
<div class="clock">
  <span class="hours">12</span>
  <span class="divider">:</span>
  <span class="minutes">00</span>
  <span class="divider">:</span>
  <span class="seconds">00</span>
</div>
```

CSS:

```css
body {
  margin: 0;
  padding: 0;
  text-align: center;
  font-size: 60px;
  font-family: sans-serif;
  background-color: black;
}

.clock {
  display: inline-block;
  position: relative;
}

.divider {
  color: gray;
  opacity: 0.5;
}

.hours,
.minutes,
.seconds {
  color: white;
}

.hours:before,
.minutes:before,
.seconds:before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: radial-gradient(ellipse at center, rgba(255, 255, 255, 0) 60%, rgba(255, 255, 255, 1) 85%);
  -webkit-mask-image: -webkit-radial-gradient(ellipse at center, rgba(0, 0, 0, 1) 60%, rgba(0, 0, 0, 0) 85%);
  mask-image: radial-gradient(ellipse at center, rgba(0, 0, 0, 1) 60%, rgba(0, 0, 0, 0) 85%);
  transition: background-color 1s ease-in-out;
}
```

JavaScript:

```javascript
function updateClock() {
  const now = new Date();
  const hours = now.getHours();
  const minutes = now.getMinutes();
  const seconds = now.getSeconds();
  document.querySelector('.hours').textContent = formatNumber(hours);
  document.querySelector('.minutes').textContent = formatNumber(minutes);
  document.querySelector('.seconds').textContent = formatNumber(seconds);
  document.querySelector('.hours').style.backgroundColor = getRandomColor();
  document.querySelector('.minutes').style.backgroundColor = getRandomColor();
  document.querySelector('.seconds').style.backgroundColor = getRandomColor();
}

function formatNumber(number) {
  return number < 10 ? `0${number}` : `${number}`;
}

function getRandomColor() {
  return `rgb(${randomInt()}, ${randomInt()}, ${randomInt()})`;
}

function randomInt() {
  return Math.floor(Math.random() * 256);
}

setInterval(updateClock, 1000);
```

Как видите, этот код состоит из трех частей: HTML, CSS и JavaScript. HTML код используется для создания разметки часов, CSS код для стилизации и JavaScript код для периодического обновления часов и изменения цвета цифр. В итоге на странице вы увидите цифры часов, где каждая цифра меняет цвет в случайный момент ее изменения.
